//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Data_Transfer_Object
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonBan
    {
        public string MaHoaDonBan { get; set; }
        public string MaTruyen { get; set; }
        public int SoLuongBan { get; set; }
        public int GiaBan { get; set; }
        public int ThanhTien { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual Truyen Truyen { get; set; }
    }
}
