//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_Data_Transfer_Object
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonBan()
        {
            this.ChiTietHoaDonBans = new HashSet<ChiTietHoaDonBan>();
        }
    
        public string MaHoaDonBan { get; set; }
        public System.DateTime NgayBan { get; set; }
        public int TongTien { get; set; }
        public string MaNhanVienBan { get; set; }
        public string MaKHTV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonBan> ChiTietHoaDonBans { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual KhachHangThanhVien KhachHangThanhVien { get; set; }
    }
}
